theme = "tabi"
title = "My place on the internet"
base_url = "https://www.parxevicj.dev"

compile_sass = true
default_language = "en"
generate_feed = true
build_search_index = true

[extra]
favicon = "favicon.ico"
socials = [
    { name = "github", url = "https://github.com/sukin-a/", icon = "github" },
    { name = "steam", url = "https://steamcommunity.com/id/parxevicj", icon = "steam" },
    { name = "mastodon", url = "https://social.vivaldi.net/@sukin", icon = "mastodon" },
]
menu = [{ name = "about", url = "about", trailing_slash = true }]

[markdown]
highlight_code = true
highlight_theme = "css"

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_path = true
include_content = true
