theme = "papermod"
base_url = "https://www.parxevicj.dev"

compile_sass = true
default_language = "en"
generate_feed = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "agola-dark"

[extra.papermod]
title = "My place on the internet"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["Dev blog: Software engineering - 1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = true
show_post_nav_links = false
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
#edit_post_url = ""
#copyright = ""
date_format = "%d-%m-%Y"
navigation = [
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "$BASE_URL/about", title = "Archive" },
    { url = "$BASE_URL/contact", title = "Content" },
]
home_title = ""
home_content = ""
social_icons = []
